= Upgrade notes

[NOTE]

====

Before upgrading a Rudder server, you should make a backup by following the
xref:administration:procedures.adoc#_migration_backups_and_restores[backup procedure].

====

== Plugins upgrade

If your server is connected to the Internet (directly or through a proxy), and you have configured
your account in the setup wizard (or directly in `/opt/rudder/etc/rudder-pkg/rudder-pkg.conf`), the upgrade process will take care of upgrading to
plugins to a compatible version.

If it is not the case, you will need to download the new ones from https://downloads.rudder.io[downloads.rudder.io].
and install them following the usual xref:reference:plugins:index.adoc[installation procedure].

You can check the current state of plugins with:

----

rudder package list --all

----

== Upgrade from Rudder 9.1 to 9.2

Upgrade from Rudder 9.1 is supported.

=== Migration of the rudder-users.xml file

As part of the web application hardening, the `rudder-users.xml` file has been moved from its previous location:
`/opt/rudder/etc/rudder-users.xml` to: `/opt/rudder/etc/webapp/rudder-users.xml`
This migration is handled automatically during the upgrade.

=== Hardening changes for the configuration-repository

All changes to the configuration-repository via Git must now be performed using
the `rudder-webapp` user.

=== Adding writable directories to systemd hardening

As part of the Rudder 9.2 release, the web application is now sandboxed using systemd directives.

If your configuration requires additional writable directories, add them to the
systemd hardening configuration in `/lib/systemd/system/rudder-jetty.service`
using the `ReadWritePaths` directive.
For example:

----

[Service]
ReadWritePaths=/opt/rudder /var/rudder /var/log /etc/cron.d /etc/systemd/system /path/to/writable/directory

----

== Upgrade from Rudder 8.3 or older to 9.2

Direct upgrades from 8.3 versions and older are no longer supported on 9.2.
If you are still running one of those, either on servers or nodes,
please first upgrade to one of the supported versions and then upgrade to 9.2.
